"""Public domain API for VaultGuard."""

from .engine import (
    HashChainEngine,
    calculate_block_hash,
    canonical_json,
    compute_block_hash,
    compute_payload_hash,
    create_block,
    create_genesis_block,
    create_next_block,
    generate_signature,
    hash_payload,
    sign_block,
    verify_block,
    verify_block_signature,
    verify_hmac_signature,
)
from .models import (
    ZERO_HASH,
    AuditAction,
    AuditPayload,
    ChainBlock,
    VerificationResult,
)
from .storage import (
    AppendOnlyError,
    BlockValidationError,
    CorruptLedgerError,
    LedgerStorage,
    SQLiteAuditLedger,
    SQLiteLedger,
    SQLiteStorage,
    StorageError,
    StorageOperationError,
    VaultGuardStorage,
    verify_chain_integrity,
    verify_ledger_integrity,
)

__all__ = [
    "ZERO_HASH",
    "AppendOnlyError",
    "AuditAction",
    "AuditPayload",
    "BlockValidationError",
    "ChainBlock",
    "CorruptLedgerError",
    "HashChainEngine",
    "LedgerStorage",
    "SQLiteAuditLedger",
    "SQLiteLedger",
    "SQLiteStorage",
    "StorageError",
    "StorageOperationError",
    "VaultGuardStorage",
    "VerificationResult",
    "calculate_block_hash",
    "canonical_json",
    "compute_block_hash",
    "compute_payload_hash",
    "create_block",
    "create_genesis_block",
    "create_next_block",
    "generate_signature",
    "hash_payload",
    "sign_block",
    "verify_block",
    "verify_block_signature",
    "verify_chain_integrity",
    "verify_hmac_signature",
    "verify_ledger_integrity",
]